import { describe, expect, it } from 'vitest'
import { decodeGoSecure, GoSecureDecodeError } from './go-secure.js'

const expected = {
  name: 'Contract',
  nested: { enabled: true },
  list: [1, 'two'],
}

// Generated by go_secure 0.67 with SECURE_ENCRYPTION_KEY=test-secure-encryption-key.
const rubyEncrypted = `072kJn3+/5NKF/diiNjSYw==
--0wf+pSiuXz19jDQgSWuRYXOB8/3smdR0f5FggeX20IM7uumJ+Xx0HnV5bJFs
5Zotc9b+WzOqwY/dhOYItrwHzg==
`

describe('decodeGoSecure', () => {
  it('decodes the unencrypted GoSecure marker format written by Ruby', () => {
    expect(decodeGoSecure(`**${JSON.stringify(expected)}`)).toEqual(expected)
  })

  it('decodes historical plain JSON settings', () => {
    expect(decodeGoSecure(`  ${JSON.stringify(expected)}`)).toEqual(expected)
  })

  it('decodes the encrypted GoSecure format written by Ruby', () => {
    expect(decodeGoSecure(rubyEncrypted, 'test-secure-encryption-key')).toEqual(expected)
  })

  it.each([
    ['malformed JSON', '**{'],
    ['malformed encrypted value', 'not-encrypted'],
    ['missing encryption key', rubyEncrypted],
  ])('rejects %s without exposing the stored value', (_name, value) => {
    expect(() => decodeGoSecure(value)).toThrowError(new GoSecureDecodeError())
    try {
      decodeGoSecure(value)
    } catch (error) {
      expect(String(error)).not.toContain(value)
    }
  })

  it('rejects an incorrect encryption key', () => {
    expect(() => decodeGoSecure(rubyEncrypted, 'incorrect-encryption-key')).toThrow(GoSecureDecodeError)
  })
})
