import { describe, expect, it, vi } from 'vitest'
import {
  createSharedSecret,
  exchangeSharedSecret,
  validateSharedSecretApplication,
  verifyAccessToken,
} from './public-api-auth.js'
import type { ExternalSourceRecord, PublicApiStore } from './public-read-store.js'

const source: ExternalSourceRecord = {
  id: 42,
  token: 'shared-secret',
  settings: { name: 'AAC Example', approved: true },
}

// Generated by go_secure 0.67 / Ruby Digest::SHA512 with the fixture key.
const rubyAccessToken = 'token::42-2:85a59ace42:1784700000:0123456789abcdef01234567:8c27a1d23853af70914d4b537fe64828a1dec40bd00e686825698d5f0e4099798602174fbd62e8693bff449ef0a32afa37f464fe4ff7b7f90b50be81026e15a6'
const fixtureKey = 'test-secure-encryption-key'
const tokenTime = new Date(1_784_700_000 * 1000)

function apiStore(record: ExternalSourceRecord | null = source): PublicApiStore {
  return {
    listRepositories: vi.fn().mockResolvedValue([]),
    findRepository: vi.fn().mockResolvedValue(null),
    findSymbol: vi.fn().mockResolvedValue(null),
    listSymbols: vi.fn().mockResolvedValue([]),
    listRepositorySymbols: vi.fn().mockResolvedValue([]),
    addSymbolRequest: vi.fn().mockResolvedValue(undefined),
    createExternalSource: vi.fn(async (token, settings) => ({ id: 43, token, settings })),
    findExternalSourceByToken: vi.fn().mockResolvedValue(record),
    findExternalSourceById: vi.fn().mockResolvedValue(record),
    close: vi.fn().mockResolvedValue(undefined),
  }
}

describe('public API applications', () => {
  it('trims and validates documented application fields', () => {
    expect(validateSharedSecretApplication({
      org_name: ' AAC Example ',
      org_email: ' api@example.com ',
      org_purpose: ' Symbol search ',
    })).toEqual({ name: 'AAC Example', email: 'api@example.com', purpose: 'Symbol search' })
    expect(validateSharedSecretApplication({
      org_name: 'AAC Example', org_email: 'invalid', org_purpose: '',
    })).toBeNull()
  })

  it('persists a pending external source with an injected nonce and time', async () => {
    const store = apiStore()
    const nonce = vi.fn(() => 'generated-shared-secret')

    await expect(createSharedSecret(store, {
      name: 'AAC Example', email: 'api@example.com', purpose: 'Testing',
    }, tokenTime, nonce)).resolves.toBe('generated-shared-secret')
    expect(store.createExternalSource).toHaveBeenCalledWith('generated-shared-secret', {
      name: 'AAC Example', email: 'api@example.com', purpose: 'Testing', approved: false,
    }, tokenTime.toISOString())
  })
})

describe('public API access tokens', () => {
  it('matches a Ruby-generated token fixture and documented expiry shape', async () => {
    const result = await exchangeSharedSecret(
      apiStore(),
      'shared-secret',
      tokenTime,
      () => '0123456789abcdef01234567',
      fixtureKey,
    )

    expect(result).toEqual({
      access_token: rubyAccessToken,
      expires: '2026-07-23T06:00:00Z',
    })
    await expect(verifyAccessToken(
      apiStore(), rubyAccessToken, new Date(tokenTime.getTime() + 60_000), fixtureKey,
    )).resolves.toEqual({ kind: 'valid' })
  })

  it('rejects missing sources, tampering, expiry, and a source whose level was downgraded', async () => {
    await expect(exchangeSharedSecret(
      apiStore(null), 'missing', tokenTime, () => 'nonce', fixtureKey,
    )).resolves.toBeNull()
    await expect(verifyAccessToken(
      apiStore(), `${rubyAccessToken.slice(0, -1)}0`, tokenTime, fixtureKey,
    )).resolves.toEqual({ kind: 'invalid' })
    await expect(verifyAccessToken(
      apiStore(), rubyAccessToken, new Date(tokenTime.getTime() + 36 * 60 * 60 * 1000), fixtureKey,
    )).resolves.toEqual({ kind: 'expired' })
    await expect(verifyAccessToken(
      apiStore({ ...source, settings: { approved: false } }), rubyAccessToken, tokenTime, fixtureKey,
    )).resolves.toEqual({ kind: 'invalid' })
  })

  it.each(['not-a-token', 'temp::legacy', 'token::42-2:missing-parts'])('rejects malformed token %s', async (token) => {
    await expect(verifyAccessToken(apiStore(), token, tokenTime, fixtureKey))
      .resolves.toEqual({ kind: 'invalid' })
  })
})
